### ISSUE TITLE
Drop-in replacement for Caddy template standard module ?

### ISSUE THREAD

**Issue by l4nj1n9** [infogulch/xtemplate-caddy#1]
I have just discovered this module which piques my interest. I am in fact the author of [CaddyTailor](https://github.com/taophp/caddy-tailor), which uses the standard template module extensively, diverting its use to allow the creation of content-independent themes. The themes are stored in one folder, the data in another in the form of markdown files, this being made possible thanks to a "router template". In use, I found this way of doing things somewhat messy, and I wondered if I was not going to implement my own templates module to allow the definition of folders, one for templates, one for data, from the configuration... when I discovered xtemplates.

After quickly browsing the project, I saw the `template.path` and `context.path` configuration directives which appear to be able to fulfill my goal. Furthermore, I understood that xtemplate-caddy was designed as an extension of caddy-template. Hence my question: can xtemplate-caddy be used as a drop-in replacement for caddy-template without modification? If not, what would be the points of attention?

Post Scriptum: I understood that the main interest of xtemplate-caddy consisted in the use of a database and I find that wonderful, even if it is not my concern at the moment.

**Comment by infogulch** [comment]
Hi! Thanks for your interest. 👋 

Yes xtemplate grew out of Caddy's `templates` module, and also handles some of the same functionality as `file_server`. They're similar in that they both use Go templates, they are meant to help you render files from a directory, and they have similar functionality like rendering markdown, but some of the details are quite different.

The biggest difference is probably the way you call other templates and read files. As you noticed, xtemplate splits file handling between two different directories, and treats them differently:

* Files in `template.path` are expected to be relatively static; all templates are parsed and kept in memory for the life of the server (modulo automatic reload which takes a few dozen ms) and other files are served directly from disk.
  * All files in the template directory are added as routes based on their path rooted at `template.path`. When a request comes in, the response will be the result of executing the template if its a template, other files are served directly from disk. You can also handle any route pattern by defining a template with a name that matches a [`http.ServeMux` pattern](https://pkg.go.dev/net/http#hdr-Patterns) inside any template file like `{{define "GET /categories/{category}/page/{page}"}}...{{end}}`.
  * Templates are (recursively) loaded into a single `*template.Template` instance, so they're all available to invoke from all other templates by their path rooted at `template.path` with Go template invocation syntax: `{{template "/other/template.html" .}}`
* Files in `context.path` are expected to be more dynamic, you can read and list them with [file operations](https://github.com/infogulch/xtemplate?tab=readme-ov-file#file-operations)

For your case, you'll be glad to know that the `markdown` and `splitFrontmatter` functions are unchanged (see "XTemplate functions" in [Functions](https://github.com/infogulch/xtemplate?tab=readme-ov-file#-functions)). You'll need to use the `.FileExists`/`.ReadFile` and `{{template "/call/other/template.html" .}}` instead of `include`, depending on where the file you want to load is. Another difference is that xtemplate uses `html/template` not `text/template` so your templates will need to be syntactically valid html and interpolated string content will be escaped by default [^1], though it's easy to bypass escaping with the `trustHtml` func, or alternatively you can sanitize content with the [bluemonday](https://github.com/microcosm-cc/bluemonday/) sanitizer using the `sanitizeHtml` func. Though database functionality is available if desired, it's definitely not required to use xtemplate. That said, a blog might need a page of categories and tags that can render quickly without reading all files in the context directory. 😉

[^1]: I was going to say that the `markdown` func returns trusted html already, but upon double checking I found that it does not! This should be resolved shortly. 😅

**Comment by l4nj1n9** [comment]
@infogulch Many thanks for your kind answer and the time you took to get all its parts. It seems that you dive in my code ! I will definitely give a try to xtemplate-caddy when I'll have a little extra time before me (next week ?)

In the meanwhile, I wonder: is there a (easy?) way to make xtemplate compatible with  classic caddy templates ? I mean, I should invest much time on CaddyTailor to design _nearly_ static websites, and I hope to not remain alone. The need to recompile Caddy with your module is not a problem for me, but it adds an extra step, that may be unnecessary in many cases, and may prevent some users to adopt CaddyTailor. It should be great if we can use xtemplate _only when_ a database is required.

At a first look, it seems not possible. As you wrote:
> You'll need to use the .FileExists/.ReadFile and {{template "/call/other/template.html" .}} instead of include, depending on where the file you want to load is.

Please, tell me what you think.

BTW: static blogs are great also, even when they missed categories and tags (I think some does not...) and some people even use them as... databases! Have a look to [Jekyll-DB](https://github.com/rypan/jekyll-db) and its [demo](http://labs.panchadsaram.com/jekyll-db/).

**Comment by infogulch** [comment]
As you suspected this is not possible mainly due to the way templates are loaded at start vs request time, and also because caddy's template is designed to be used together with caddy's other modules, but xtemplate is designed to be independent, though still useful if integrated into caddy. In particular, template acts as a middleware and can 'forward' a request down the caddy http middleware chain and act on the response which is not something xtemplate can currently do. I wouldn't worry about the database functionality if you're not going to use it, if you don't compile with a driver you can't initialize it anyway, and it doesn't take up much space.

As far as distribution, you can use the xcaddy image to build a custom image with xtemplate. Maybe I can look into documenting that process and publishing a caddy image with xtemplate pre-installed.

**Comment by l4nj1n9** [comment]
Well, I'm not sure to fully understand the implications of your last message, as I'm not as familiar as with the architecture of Caddy. When you wrote that xtemplate is designed to be independent, do you that it won't work with other modules, for example with [Caddy Security](https://github.com/greenpau/caddy-security) which seems very interesting ?

> Maybe I can look into documenting that process and publishing a caddy image with xtemplate pre-installed.

For sure, you should!

**Comment by infogulch** [comment]
Caddy middlewares like Caddy Security, `template`, and `file_server` receive requests by implementing Caddy's custom middleware interface [`caddyhttp.MiddlewareHandler`](https://github.com/caddyserver/caddy/blob/c27425ef5d112bb71e8b7bf4abfb73464fbf869a/modules/caddyhttp/caddyhttp.go#L65-L76). The relevant part is the added `next caddyhttp.Handler` param relative to the stdlib's [`http.Handler`](https://pkg.go.dev/net/http#Handler). This is how you can chain multiple handlers together like this:

```Caddyfile
    file_server
    templates
    route {
        try_files /subdomains/{http.request.host.labels.1}/{path} {path} index.html
    }
```

In this case, a request is routed to `file_server` first and if it doesn't find a file it will forward the request to the next handler, `templates` in this case which forwards to `try_files`. Then it goes the other way: `try_files` finds the file and responds with its bytes, then `templates` parses the bytes as a template and responds with the result of executing the template, and then `file_server` just passes that back unmodified. This whole chain occurs for every request [^1], and is a pretty typical "middleware handler" pattern.

xtemplate can act as a middleware, but the way it is "independent" is that it doesn't forward unhandled requests down the chain. Middlewares like caddy security can be put ahead of it and it should work fine.

[^1]: This is one of the reasons for xtemplate's design: the templates are already parsed and sitting in memory which allows it to entirely avoid reading from disk and parsing its contents on every request which should be a sizable performance win, though I haven't measured it yet. 😅

**Comment by l4nj1n9** [comment]
Oh. Surprisingly, I was not aware of chaining all those middlewares 🤣 
Thanks for your answers. I definitely think that good work can be done with xtemplate and I will give it a try very soon.

**Comment by infogulch** [comment]
You're welcome. Let me know how its going, I'm keen on making xtemplate useful for use cases like this. :)
