### ISSUE TITLE
User session ? (and SQL injections ?)

### ISSUE THREAD

**Issue by l4nj1n9** [infogulch/xtemplate-caddy#2]
Hi @infogulch,

I haven't tested xtemplate-caddy yet, but my reflection goes deeper in the while. Maybe I'm seeing a new, at least new to my eyes, paradigm emerging, [Locality Of Behavior(LOC)](https://htmx.org/essays/locality-of-behaviour/) and a new way of making my job, a new stack for web apps. Thanks for mentioning htmx, that leads me to hyperscript and hypermedia... All this stuff is very exciting. On this way, some questions appeared.

First, the easiest as a quick look in your code maybe provide the answer easily (for a Go developer, which I'm not...): is xtemplate sqlijections resistant ? I suppose it is.

Second: is there a way to handle users with xtemplate ? I understand that xtemplate is essentially a shortcut for requests to databases, but to build a useful app, it is required to manage user rights on tables and table rows.
Session, authentication, and so on may be handled by a another module ([Caddy Security](https://github.com/greenpau/caddy-security) seems great for that), but, when a user is logged, how to provide the relevant informations, userid at least, to SQL requests in xtemplate ?

PS: Oh, and what about CSRF ?

**Comment by l4nj1n9** [comment]
I think I have an answer for the second question. I thinks we can combine [custom HTTP Headers provided by Caddy Security](https://docs.authcrunch.com/docs/authorize/headers#custom-headers) with the [`.Req.Header`](https://github.com/infogulch/xtemplate?tab=readme-ov-file#user-content-request-data-and-response-control) provided by xtemplate to manage access to tables and tables rows.

And, regarding CSRF, I think we can just store a token in a table and inject it in a form to check it afterwards.

What do you think ?

**Comment by infogulch** [comment]
> Thanks for mentioning htmx, that leads me to hyperscript and hypermedia... All this stuff is very exciting.

It makes me glad to hear that these ideas are also exciting to you!

> is xtemplate sqlijections resistant ?

I guess there's two interpreted languages here, SQL and HTML, so two types of 'injection' we have to contend with. By default xtemplate is safe from both. Consider an example:

```html
<p>Hi! My name is: {{ .QueryVal `SELECT name FROM users WHERE id = ?` (.Req.Header.Get "user-id") }}</p>
```

This will be safe from both types of injection. Safe from SQL injection because we're using parameterized queries, and safe from HTML injection (sometimes called Cross-site Scripting (XSS)) because the `html/template` package automatically escapes string content embedded by templates, for example if the user's name contained html that tried to execute a script.

That said you can write it differently to make yourself vulnerable again:

> [!CAUTION]
> The following template is intentionally vulnerable to both SQL and HTML injection, written for demonstration purposes.

```html
<p>Hi! My name is: {{ trustHtml .QueryVal (printf `SELECT name FROM users WHERE id = %s` (.Req.Header.Get "user-id")) }}</p>
```

So, don't use `trustHtml` unless you're very sure that its safe, and never build query strings with user data.

---

Safety to injections is mentioned briefly in the features section of the `xtemplate` readme.

---

Yes, those are the strategies that I would use for user management and CSRF.
